### ISSUE TITLE
Improve `use_touchstone()`

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#100]
* Don't write `touchstone` directory to `.Rbuildignore` if already present.
* add a `force = FALSE` argument.

**Comment by assignUser** [comment]
What do you want `force=FALSE` to do?

**Comment by lorenzwalthert** [comment]
The current behavior. Basically not replacing files if they exist. `force = TRUE` would replace existing workflow or other files, similar to `precommit::use_precommit()`.
