### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#101]
I think it would be nice to use a progress bar so if you go to see the running GHA, you can see how much is left instead of / in addition to this generic status update.
![Screenshot 2022-01-16 at 17 16 54](https://user-images.githubusercontent.com/10477073/149668210-7e56cec3-a2dd-4eb9-9304-d7af93c268bd.png)

**Comment by assignUser** [comment]
Yeah I thought about that too (e.g. {progressr}) but I am not sure if that is possible with the way gha logs work so I never tried it :D

**Comment by assignUser** [comment]
I just tested it with {progress} and the log just pauses until the progressbar is done, I don't think this is possible. But I will have another look at the grouping that doesn't really seem to work at the moment. Then each benchmark would be grouped, that would give an overall indivation at what point in `script.R` the process is and make it not as messy to look at xD

**Comment by assignUser** [comment]
I think this is much better than before, what do you think @lorenzwalthert: 
https://github.com/assignUser/simstudy/runs/4840074147?check_suite_focus=true#step:2:2501

**Comment by assignUser** [comment]
For the stuff above the benchmarks: I think the easiest way here is to group the output from `branch_install` and let the rest (more or less just asset pinning) stand on its own as doing else is not really worth the effort imho.

I agree your second idea would look very nice but is not possible as I don't think you can change group names once they are set + your other concerns :D

**Comment by assignUser** [comment]
https://github.com/assignUser/simstudy/runs/4840898017?check_suite_focus=true#step:2:2055
