### ISSUE TITLE
if Benchmark fails, no failed check is visible or comment posted

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#105]
Now it’s silent, which is dangerous if the PR has big speed implications.

**Comment by assignUser** [comment]
I think the biggest "danger" here is if the comment job fails, as it is not listed in the pr-checks list. So everything would show up :heavy_check_mark:

**Comment by lorenzwalthert** [comment]
Yes, the two things in conjunction. The comment job should have an `if: fails()` clause that comments in the case of failure (hoping that that itself won't fail).

**Comment by assignUser** [comment]
We can create a job in the comment workflow that only runs if the receive flow failed.

**Comment by lorenzwalthert** [comment]
And what if the comment workflow fails for some other reason?

**Comment by assignUser** [comment]
mhm that's a bit of a "snake eating it's own tail"-situation... It would be best if we could turn the comment action into a pr check. That way it would be noticable if the action fails? I think this might be possible with the checks api... I'll look into it.

**Comment by assignUser** [comment]
Found a solution, pr incomming
![image](https://user-images.githubusercontent.com/16141871/152695175-fdeccfb0-5e2a-4842-9a55-77ec35428ae1.png)
![image](https://user-images.githubusercontent.com/16141871/152695234-6c358319-dc69-47dd-9fcf-4cf1162ac298.png)

**Comment by assignUser** [comment]
https://github.com/assignUser/simstudy/pull/20#partial-pull-merging
