### ISSUE TITLE
possibility of turning off notification on every push?

### ISSUE THREAD

**Issue by njtierney** [lorenzwalthert/touchstone#111]
Hello!

I was wondering if it might be possible to turn off notifications on every push, and instead perhaps ask the bot for a speed comparison when wanted?

**Comment by assignUser** [comment]
Zep that should be possible, I'll have a look.

**Comment by assignUser** [comment]
A quick update: this is possible but the action triggered by the issue command does not have the `HEAD` in it's payload so we have to get that manually. I'll look into that today.

**Comment by assignUser** [comment]
This was a bit more involved than anticipated. 
@njtierney I have opened a pr with the changes to your workflow file to enable this: https://github.com/greta-dev/greta/pull/517

@lorenzwalthert While working on this I noticed that benchmarks from external forks would use the origin base branch and not the upstream base branch, this could lead to misleading benchmark results e.g. if the fork is not up to date. I implemented logic in the "manual-trigger" branch to resolve this issue. (with an option to force benchmarking against upstream in "test" pr within forks)

**Comment by njtierney** [comment]
Thanks, @assignUser ! Sorry for the delay getting back to you, just sorting my life out after some time away on holiday.

Can I ask, what is the command to trigger the benchmark loading on PR?

**Comment by assignUser** [comment]
@njtierney Hey, no worries! 🏖️ 
Yes exactly `/benchmark`  you could also change it to something else if you'd like by replacing that in the workflow.file

**Comment by njtierney** [comment]
Awesome! Thank you!
