### ISSUE TITLE
Emojis no longer rendered properly in the comments

### ISSUE THREAD

**Issue by IndrajeetPatil** [lorenzwalthert/touchstone#126]
E.g. https://github.com/r-lib/styler/pull/1173#issuecomment-1890970457

<img width="827" alt="Screenshot 2024-01-14 at 15 45 15" src="https://github.com/lorenzwalthert/touchstone/assets/11330453/fc39d128-844e-4f7d-ae19-697ba0eca9c5">

**Comment by assignUser** [comment]
* :ballot_box_with_check:tet

**Comment by assignUser** [comment]
hm, maybe some changes to how automatic comments are treated?

**Comment by assignUser** [comment]
Editing around in another comment shows that they are rendered again when the leading html space is removed:
* :ballot_box_with_check: define_data: 15.4ms -> 15.4ms [-2.34%, +1.44%]
* &nbsp;&nbsp;:ballot_box_with_check:dist_beta: 211ms -> 211ms [-5.83%, +5.96%]

**Comment by olivroy** [comment]
Still an issue  https://github.com/r-lib/styler/pull/1189#issuecomment-2025350896  and in comment above

Probably just needs as space to make it work ?

![image](https://github.com/lorenzwalthert/touchstone/assets/52606734/7cb12ca6-eb7a-48f8-baea-efe95c952747)

**Comment by lorenzwalthert** [comment]
Also don’t geht that. Styler seems to use the main tag, so it should use the latest commit on main: https://github.com/r-lib/styler/blob/208d9c7abb4eb44436695a68a19ea979c99ce921/.github/workflows/touchstone-comment.yaml#L20

However, I still see the ballot_box_with_check.. but the PR #127 changed that so I am confused. Do we need to release a new tag?

**Comment by assignUser** [comment]
In this repo the emojis show up fine: https://github.com/kgoldfeld/simstudy/pull/221#issuecomment-2016849698
So it seems to be a styler specific problem which I don't understand...

**Comment by assignUser** [comment]
https://github.com/lorenzwalthert/touchstone/blob/main/actions/receive/action.yaml#L103 

Sorry, I didn't think of that when we merged the fixes.

**Comment by lorenzwalthert** [comment]
Ok, so should we create a new tag and move the default? I guess no one would want to use `@v1` anymore and there are no breaking changes. Should we release `@v1.0.1` (as SemVer would suggest)? or what's the preferred versioning scheme with GitHub Actions?

**Comment by assignUser** [comment]
Usually for actions you would tag `@v1.0.1` and additionally move the v1 tag to head

**Comment by lorenzwalthert** [comment]
Great. Can you do that?

**Comment by assignUser** [comment]
Done, that should propagate the fix to styler!
