### ISSUE TITLE
Reset "lib"-dir during local testing

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#35]
When testing locally using `run_script` touchstone will skip installing the package if it is already installed in the dir matching the current `ref`, which is good in case there are just changes to `script.R` but is a bit annoying when changing the package itself and using branch names as refs .

It would be nice if touchstone checked the actual commit sha or something, of the installed package version instead of just the branch name.  Maybe this functionality already exists and I just haven't turned it on ^-^.

**Comment by assignUser** [comment]
I had a look at the code and this is actually `remotes::install_local`, the brute force method would be setting `force = TRUE` but this would also remove the nice speed up when testing locally and not changing the package itself... maybe adding the short hash to the lib dir name would be a solution?

**Comment by lorenzwalthert** [comment]
Right... I suggest to force re-installation on source change in `R/` and `src/` (if existent). You can try it out with 
```r
# better restart R since I changed `.onLoad()`
remotes::install_github('lorenzwalthert/touchstone#37')
```

Does this make sense?
