### ISSUE TITLE
Add directory that is copied with script.R

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#39]
While setting up the tests for our package I noticed that `source`ing additional scripts is a good way to keep `script.R` tidy but this requires the additional scripts to exist on both branches, as only `script.R` is copied to a neutral directory by `run_script`.

I would like to introduce the possibility to define a directory that (or its contents) will be copied alongside `script.R`. Maybe via an option or a helper function?

This would make keeping `script.R` tidy for people like me who need to use a lot of verbose setup and test code.
Additionally, it would allow to repurpose expressions already defined for normal {bench} tests without copying their code.

**Comment by lorenzwalthert** [comment]
Thanks. So the setup I envisioned was:

1. Define benchmarking code /data / setup in the main branch.
2. Make PRs where you don't change the benchmarking setup, only the code that you want to benchmark.

If you want to change or add benchmarks as you go with a PR, I agree this is not optimal. For that reason, I agree that it would be good to have a directory available where other assets can be placed. Important to note is:

* the working directory is still the package root.
* to access assets,  one has to construct the path to them via `touchstone.tempdir` option or similar as proposed in #40.

**Comment by lorenzwalthert** [comment]
I'll comment on the implementation now.
