### ISSUE TITLE
Create "Getting started" vignette

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#42]
Now that the package scope is increased thanks to your collaboration, maybe we need a getting started vignette to make sure the user understands things (in the context of this issue: the difference between accessing files that are branch dependent and things that are not) and make the README a bit more slim.

_Originally posted by @lorenzwalthert in https://github.com/lorenzwalthert/touchstone/issues/39#issuecomment-910074977_

* [x] Also add documentation about #43
* [ ] Also add documentation about #29
* [x] Update screenshot in README

**Comment by assignUser** [comment]
The vignette might also be a good place for #29

**Comment by lorenzwalthert** [comment]
Thanks 😄

**Comment by assignUser** [comment]
Also add documentation about #43
