### ISSUE TITLE
Better display of sub-second benchmarks

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#53]
Sub second benchmarks can look weird/not informative:
![image](https://user-images.githubusercontent.com/16141871/132310389-b1f64c62-b5d3-4f82-b5f4-28e1402ba8e5.png)
![image](https://user-images.githubusercontent.com/16141871/132310573-9f1a47c0-4d87-47bc-8327-e6501ddac66d.png)

I  would like to see if we can format them nicely.

**Comment by lorenzwalthert** [comment]
Yes, formatting should be dependent on the output. I think it's currently hardocded to be in seconds with no decimal places. Maybe using`‘prettyNum()` or similar?
