### ISSUE TITLE
PR comments have wrong percentage change and significance  

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#58]
![BAAFBD10-7063-4ED9-AEFC-B7EBB2EBF728](https://user-images.githubusercontent.com/10477073/132984719-bc0a5195-a23e-4ee6-af65-def6adfc6fd1.png)
Seems like percentage calculations (and emojis) are not correct anymore, I think related to deine recent changes. 

https://github.com/r-lib/styler/pull/715#issuecomment-917483198

**Comment by assignUser** [comment]
@lorenzwalthert yeah sorry my fault... `bench::as_bench_time`coerces negative numbers to *1ns* which is rounded to zero... sorry... pr coming up

**Comment by assignUser** [comment]
![image](https://user-images.githubusercontent.com/16141871/132990106-fe1b2393-49cd-41f8-b688-21057af8735e.png)
👍
