### ISSUE TITLE
Hard deprecate the use of strings in inputs

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#61]
This is very confusing, because in general, a character vector of length one is identical to a string. Not in our case:

``` r
f <- function(...) {
  dots <- rlang::enexprs(...)
  print(dots)
}

f("x")
#> [[1]]
#> [1] "x"
f(c("x"))
#> [[1]]
#> c("x")
```

<sup>Created on 2021-09-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This made https://github.com/lorenzwalthert/touchstone.test/pull/4 fail. @assignUser any objections?

**Comment by assignUser** [comment]
I agree! Additionally it is not only confusing but I don't see any advantages string input brings.
