### ISSUE TITLE
Asset pinning not working as expected

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#68]
When I pin `inst/WORDLIST`, I assume it to be available in `path_pinned_asset('inst/WORDLIST')`. Do you agree? I just added https://github.com/lorenzwalthert/touchstone/pull/67 with this example as a unit test and it fails.

**Comment by lorenzwalthert** [comment]
Probably we can make a more minimal example than I did...

**Comment by assignUser** [comment]
@lorenzwalthert sure I will have a look!

btw it would make things a bit easier if you could give me write access so I can work on the branches you created for these issues, feel free to turn on branch protection for main etc. if you like :)

**Comment by lorenzwalthert** [comment]
I pushed two examples, one I think matches the helpfile example for `pin_assets()`.

**Comment by assignUser** [comment]
Awesome thanks!

I have found the issue, this problem is caused by the  {callr} subprocess having another temp folder then the calling session:
## Setup
``` r
refs <- c("devel", "main")
withr::local_envvar(list(
    GITHUB_BASE_REF = refs[[2]],
    GITHUB_HEAD_REF = refs[[1]]
))
#> Setting deferred event(s) on global environment.
#>   * Execute (and clear) with `withr::deferred_run()`.
#>   * Clear (without executing) with `withr::deferred_clear()`.
pkg_name <- "b32jk"
path_test_pkg <- touchstone:::local_package(pkg_name, branches = refs)
#> ✖ Could not find git repository from current working directory!
#> ℹ Please manually set the option "touchstone.git_root".
```
## The interesting bit
``` r
touchstone:::get_asset_dir("main")
#> /tmp/RtmpnCe7tT/base
callr::r(function() {
    touchstone:::get_asset_dir("main")
})
#> /tmp/RtmpookSY9/base
```

<sup>Created on 2021-10-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I will think about how to solve this issue.
