### ISSUE TITLE
Use macOS as runner?

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#76]
I just learned that the macOS runners have an extra core and twice the amount of ram:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Should we switch over? Also would an option to parallelise the benchmarks make sense? If the code does not use multiple cores we could run multiple test at once? Just a thought :D maybe to complicated...

**Comment by assignUser** [comment]
Also as a by product of this thought: do we need to switch branches between refs with the separate versions in the libpaths and asset pinning?

**Comment by lorenzwalthert** [comment]
Switching over to macOS sounds like a good idea by default. I would advise against using multiple cores to run benchmarks in parallel. Even if the R code to benchmark uses one core, you may depend on other code that uses multiple cores under the hood, initiates external processes or other languages where there is parallelization.

**Comment by lorenzwalthert** [comment]
> Also as a by product of this thought: do we need to switch branches between refs with the separate versions in the libpaths and asset pinning?

Can you elaborate a bit on that. I don't get it (at least not in the context of non-parallel benchmarking) 🙈

**Comment by assignUser** [comment]
> the potential problems it causes large.

Yeah I also came to this conclusion while thinking about it some more :D

**Comment by assignUser** [comment]
> Can you elaborate a bit on that? I don't get it (at least not in the context of non-parallel benchmarking) see_no_evil

When running a block A: `c("main","feature")` it currently works like this:
* checkout `main`
* switch `.libPaths` to temp lib containing main version of package
* run 1 iteration of the benchmark
* checkout `feature`
* switch `.libPaths` to temp lib containing `feature` version of package

I was asking if there is a technical need to checkout the branches, as the package is available in the correct version via `.libPaths` and any assets outside of `script.R` should be accessed via `path_pinned_asset` or am I missing something?

The benefit would be some time savings and a cleaner log (which is still a bit uninformative I feel, e.g. which benchmark is currently running would be a good info, maybe using gha log group?)

**Comment by lorenzwalthert** [comment]
Also, I just recall that I decided to use Linux since we can use binaries + time travel functionality of RSPM ...

**Comment by lorenzwalthert** [comment]
> any assets outside of script.R should be accessed via path_pinned_asset or am I missing something?

I did not create {touchstone} with that in mind. While the source code difference is captured in the installed package, other changes are not (e.g. files in `inst/`), the touchstone script may also depend on these non-`R/` files and I think we want that to be possible.

**Comment by lorenzwalthert** [comment]
I think we can close this for now.
