### ISSUE TITLE
API Review

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#77]
* API review, i.e. 
  * `benchmark_run_ref()` should probably be called `benchmark_run()` only.
  * Not sure we should continue to use the notion *ref(s)*. Because it might be misleading, since the refs are mostly branches (i.e. heads), not arbitrary commits on a branch. Also, you can create a branch from an arbitrary commit and benchmark it, so for people who are not git geeks, using *branch* might make more sense than *ref*. This affects exported function names and arguments and documentation. 

_Originally posted by @lorenzwalthert in https://github.com/lorenzwalthert/touchstone/issues/31#issuecomment-962508956_

**Comment by lorenzwalthert** [comment]
Ok, I'll give it a go now. Or did you already start?

**Comment by assignUser** [comment]
Hey, sorry I haven't had the time recently due to work (submission deadline coming up^^) but I should be able to work on it next week. But feel free to go ahead right now and I'll jump in later!
