### ISSUE TITLE
`activate()` should override `n` in `benchmark_run()`

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#88]
In `benchmark_run(..., n = )`, `n` should default on a global R option that is changed on `activate()`. This simplifies local debugging.

```r
library(touchstone)
activate()
benchmark_run(myexpr = sys.sleep(4)) # should run once
````

So I propose: 
```r
benchmark_run <- function(expr_before_benchmark =
                            {},
                          ...,
                          branches = c(
                            branch_get_or_fail("GITHUB_BASE_REF"),
                            branch_get_or_fail("GITHUB_HEAD_REF")
                          ),
                          n = 100
                          path_pkg = ".") {
  # ...  override n with `'touchstone.n_runs'` if set.
}
```
`activate()` should set '`touchstone.n_runs'` to 1 (and deactivate should restore the previous value).

**Comment by assignUser** [comment]
Similar to #89 I think it would make sense to only override `n` with the env var when in interactive mode. That way the values set in `script.R` are the deciding factor without some "hidden" values interfering.
