### ISSUE TITLE
Standalone touchstone action?

### ISSUE THREAD

**Issue by assignUser** [lorenzwalthert/touchstone#91]
It might be nice to extract the inner workings of the actions into a separate repo to make touchstone easier to use?
Something like https://github.com/r-lib/actions/tree/v2-branch/check-r-package

**Comment by lorenzwalthert** [comment]
Fully agree, that’s the elegant way. I won’t have time for that, but it would be great if anyone wants to contribute that. @assignUser are you interested? I habe no idea how complex that is.

**Comment by assignUser** [comment]
@lorenzwalthert should be pretty much copy&past + some input options I guess? I'll check it out :)
Do you want to create the repo for the action?

**Comment by lorenzwalthert** [comment]
Ok, great. Why not hosting it as part of this repo?

**Comment by assignUser** [comment]
I thought actions made available to others needed standalone repos but maybe that's not true, I'll check it out!
