### ISSUE TITLE
New actions fail on repo with fork

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/touchstone#98]
In {styler}, I can't seem to make the action pass after replacing the Workflows with the templates from {touchstone}:
https://github.com/r-lib/styler/actions/runs/1699543116

Any idea why? There is a corresponding [PR](https://github.com/r-lib/styler/pull/902) that shows passing but the comment from {touchstone} is missing. From the error message, it seems like the *secrets* context is missing.

**Comment by assignUser** [comment]
I think we have to pass the token into the action explicitly (No idea why it worked during my tests...).  I will create a quick patch for main.

**Comment by lorenzwalthert** [comment]
Wir #99, still no luck. Now seems an unrelated {pak} problem. https://github.com/r-lib/styler/runs/4828086477?check_suite_focus=true

**Comment by assignUser** [comment]
I had that error with simstudy the last days, usually running the job again
works. I will open an issue in the actions repo.

Lorenz Walthert ***@***.***> schrieb am Sa., 15. Jan. 2022,
20:32:

**Comment by lorenzwalthert** [comment]
ok, will try re-run.

**Comment by assignUser** [comment]
https://github.com/r-lib/actions/issues/483

**Comment by lorenzwalthert** [comment]
Thanks for the fix.

**Comment by lorenzwalthert** [comment]
And it failed again https://github.com/r-lib/styler/runs/4828631586?check_suite_focus=true... Hope this can be fixed or it's just by chance.

**Comment by assignUser** [comment]
Ugh, that's annoying... I think it's by chance maybe some request times out? They are using RSPM for dependency resolution afaik so maybe somethings spotty there? I'll add that run to the issue.

**Comment by assignUser** [comment]
It works! :tada:  https://github.com/r-lib/styler/pull/868#issuecomment-1013752623

**Comment by lorenzwalthert** [comment]
Indeed, it did 🥳. Let's see how it goes with the {pak} error in the future. I previously started using a more recent RSPM as you [suggested](https://github.com/lorenzwalthert/touchstone/pull/92#issue-1096460812).
